name: CI

on:
  pull_request: # Виконується на кожен Pull Request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Або інша версія вашого Node.js

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format --check

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test
