name: CI Workflow

on:
  pull_request:
    branches:
      - main # або інша ваша основна гілка

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Ваша версія Node.js

      - name: Ensure Husky files are executable
        run: chmod -R +x .husky/

      - name: Install Husky globally
        run: npm install -g husky

      - name: Install dependencies
        run: npm install

      - name: Install Husky
        run: npx husky install

      - name: Ensure Husky files are executable
        run: chmod -R +x .husky/

      - name: Ensure ESLint is executable
        run: chmod +x node_modules/.bin/eslint

      - name: Ensure ESLint is executable
        run: chmod +x node_modules/.bin/eslint

      - name: Run ESLint
        run: npx eslint .

      - name: Run Prettier
        run: npm run format -- --check .

      - name: Run tests
        run: npm test # Передбачає, що у вас є тести

