name: CD Pipeline

on:
  push:
    branches:
      - main # або ваша основна гілка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Отримати код з репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Встановити sshpass
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # 3. Створити папку на сервері (якщо її немає)
      - name: Create deployment folder on server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SERVER }} "mkdir -p ${{ secrets.DEPLOY_PATH }}"

      # 4. Копіювати файли на сервер
      - name: Copy files to server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.USERNAME }}@${{ secrets.SERVER }}:${{ secrets.DEPLOY_PATH }}

      # 5. Перезапустити сервер (опціонально)
      - name: Restart application (optional)
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SERVER }} "sudo systemctl restart myapplication"