name: Deploy with SSH

on:
  push:
    branches:
      - main # Замість main ви можете вказати будь-яку іншу гілку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "SERVER: $SERVER"
          mkdir -p ~/.ssh
          # Додаємо сервер до відомих хостів для уникнення підтвердження
          ssh-keyscan -H "$SERVER" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy app via SSH
        run: |
          # Підключення через sshpass з паролем
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER "mkdir -p $DEPLOY_PATH"
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SERVER: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
