name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install expect
        run: sudo apt-get install expect

      - name: Deploy files to server
        run: |
          expect -c '
            spawn ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER }} "mkdir -p ${{ secrets.DEPLOY_PATH }}"
            expect "password:"
            send "${{ secrets.SSH_PASSWORD }}\r"
            interact
          '
          scp -r ./ ${{ secrets.USERNAME }}@${{ secrets.SERVER }}:${{ secrets.DEPLOY_PATH }}
