name: CD Pipeline

on:
  push:
    branches:
      - main # або ваша основна гілка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }} # Приватний ключ з секретів GitHub

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /path/to/your/project
            git pull origin main
            # додайте сюди команду для перезапуску вашого додатку, наприклад:
            npm install
            pm2 restart your-app
          EOF
