name: Deploy with SSH

on:
  push:
    branches:
      - main # Замість main ви можете вказати будь-яку іншу гілку

jobs:
  deploy:
    runs-on: ubuntu-latest

steps:
  - name: Checkout code
    uses: actions/checkoutgv2

  - name: Install sshpass
    run: sudo apt-get install sshpass

  - name: Create deployment folder on server
    run: |
      sshpass -p "${{ secrets.SSH_PASSNORD }}" ssh -o StricthostKeyCheckingzno ${{ secrets USERNAME }}g${{ secrets. SERVER }}

  - name: Copy files to server
    run: |
      sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -r ./ ${{ secrets.USERNAME }}@${{ secrets.SERVER }}:${{ secrets.DEPLOY_PATH }}
    env:
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      USERNAME: ${{ secrets.USERNAME }}
      SERVER: ${{ secrets.SERVER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

  - name: Restart server or services
    run: |
      sshpass -p “${{ secrets.SSH_PASSHORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets USERNAME }}gS{{ secrets. SERVER }}
